In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

In [2]:
df=pd.read_csv("drug200.csv")
df

     Age Sex      BP Cholesterol  Na_to_K   Drug
0     23   F    HIGH        HIGH   25.355  drugY
1     47   M     LOW        HIGH   13.093  drugC
2     47   M     LOW        HIGH   10.114  drugC
3     28   F  NORMAL        HIGH    7.798  drugX
4     61   F     LOW        HIGH   18.043  drugY
..   ...  ..     ...         ...      ...    ...
195   56   F     LOW        HIGH   11.567  drugC
196   16   M     LOW        HIGH   12.006  drugC
197   52   M  NORMAL        HIGH    9.894  drugX
198   23   M  NORMAL      NORMAL   14.020  drugX
199   40   F     LOW      NORMAL   11.349  drugX

[200 rows x 6 columns]

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Age          200 non-null    int64
 1   Sex          200 non-null    object
 2   BP           200 non-null    object
 3   Cholesterol  200 non-null    object
 4   Na_to_K      200 non-null    float64
 5   Drug         200 non-null    object
dtypes: float64(1), int64(1), object(4)
memory usage: 9.5+ KB

In [4]:
df.isnull().sum()

Age            0
Sex            0
BP             0
Cholesterol    0
Na_to_K        0
Drug           0
dtype: int64

In [5]:
df.duplicated().sum()

np.int64(0)

In [6]:
df['Drug'].value_counts()

Drug
drugY    91
drugX    54
drugA    23
drugC    16
drugB    16
Name: count, dtype: int64

In [8]:
pd.crosstab(pd.cut(df["Na_to_K"],bins=5),df["Drug"])

Drug              drugA  drugB  drugC  drugX  drugY
Na_to_K
(6.237, 12.665]      16     11     13     41      0
(12.665, 19.06]       7      5      3     13     36
(19.06, 25.456]       0      0      0      0     26
(25.456, 31.851]      0      0      0      0     20
(31.851, 38.247]      0      0      0      0      9

In [9]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [10]:
for i in df.columns:
    if df[i].dtype=='object':
        df[i] = le.fit_transform(df[i])

In [11]:
df

     Age  Sex  BP  Cholesterol  Na_to_K  Drug
0     23    0   0            0   25.355     4
1     47    1   1            0   13.093     2
2     47    1   1            0   10.114     2
3     28    0   2            0    7.798     3
4     61    0   1            0   18.043     4
..   ...  ...  ..          ...      ...   ...
195   56    0   1            0   11.567     2
196   16    1   1            0   12.006     2
197   52    1   2            0    9.894     3
198   23    1   2            1   14.020     3
199   40    0   1            1   11.349     3

[200 rows x 6 columns]

In [13]:
x=df.drop("Drug",axis=1)
y=df["Drug"]

In [14]:
x

     Age  Sex  BP  Cholesterol  Na_to_K
0     23    0   0            0   25.355
1     47    1   1            0   13.093
2     47    1   1            0   10.114
3     28    0   2            0    7.798
4     61    0   1            0   18.043
..   ...  ...  ..          ...      ...
195   56    0   1            0   11.567
196   16    1   1            0   12.006
197   52    1   2            0    9.894
198   23    1   2            1   14.020
199   40    0   1            1   11.349

[200 rows x 5 columns]

In [15]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=62)

In [16]:
from sklearn.svm import SVC

In [17]:
model1=SVC()

In [18]:
model1.fit(x_train,y_train)

y1_pred=model1.predict(x_test)

In [19]:
y1_pred

array([4, 4, 3, 3, 4, 3, 4, 3, 4, 3, 3, 3, 4, 3, 4, 3, 4, 4, 3, 4, 4, 4,
       4, 4, 4, 3, 4, 3, 3, 3, 4, 3, 4, 3, 3, 3, 4, 3, 3, 3])

In [20]:
from sklearn.metrics import *

In [26]:
print(f"Accuracy Score is : {accuracy_score(y1_pred,y_test)}")

Accuracy Score is : 0.725

In [23]:
model2=SVC(kernel='linear')
model2.fit(x_train,y_train)

y2_pred=model2.predict(x_test)

In [27]:
print(f"Accuracy Score is {accuracy_score(y2_pred,y_test)}")

Accuracy Score is 1.0

In [30]:
model3=SVC(kernel='poly')
model3.fit(x_train,y_train)

y3_pred=model3.predict(x_test)

In [31]:
print(f"Accuracy Score is {accuracy_score(y3_pred,y_test)}")

Accuracy Score is 0.65

In [32]:
model4=SVC(kernel='sigmoid')
model4.fit(x_train,y_train)

y4_pred=model4.predict(x_test)

In [33]:
print(f"Accuracy Score is {accuracy_score(y4_pred,y_test)}")

Accuracy Score is 0.275